FROM ruby:3.3.8-slim-bookworm

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential libpq-dev libvips libyaml-dev curl git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

COPY Gemfile Gemfile.lock .ruby-version ./

ENV BUNDLE_PATH=/usr/local/bundle
RUN bundle install

COPY . .

RUN bundle exec bootsnap precompile --gemfile app/ lib/
