# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@github/hotkey", to: "@github--hotkey.js"
pin "@simonwep/pickr", to: "@simonwep--pickr.js"

# D3 packages
pin "d3"
pin "d3-array", to: "shims/d3-array-default.js"
pin "d3-axis"
pin "d3-brush"
pin "d3-chord"
pin "d3-color"
pin "d3-contour"
pin "d3-delaunay"
pin "d3-dispatch"
pin "d3-drag"
pin "d3-dsv"
pin "d3-ease"
pin "d3-fetch"
pin "d3-force"
pin "d3-format"
pin "d3-geo"
pin "d3-hierarchy"
pin "d3-interpolate"
pin "d3-path"
pin "d3-polygon"
pin "d3-quadtree"
pin "d3-random"
pin "d3-scale"
pin "d3-scale-chromatic"
pin "d3-selection"
pin "d3-shape", to: "shims/d3-shape-default.js"
pin "d3-time"
pin "d3-time-format"
pin "d3-timer"
pin "d3-transition"
pin "d3-zoom"
pin "delaunator"
pin "internmap"
pin "robust-predicates"
pin "@floating-ui/dom", to: "@floating-ui--dom.js"
pin "@floating-ui/core", to: "@floating-ui--core.js"
pin "@floating-ui/utils", to: "@floating-ui--utils.js"
pin "@floating-ui/utils/dom", to: "@floating-ui--utils--dom.js"
pin "d3-sankey"
